In [1]:
#线性代数
#一个形状为（2，3，4）的矩阵是什么样的呢，每去掉一层括号，就往后一一层,例如去掉一层括号后就变成了俩个3*4的矩阵
import torch
A = torch.arange(24).reshape(2,3,4)
A

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [2]:
#两个矩阵按元素做乘法
B = torch.arange(24).reshape(2,3,4)
A * B

tensor([[[  0,   1,   4,   9],
         [ 16,  25,  36,  49],
         [ 64,  81, 100, 121]],

        [[144, 169, 196, 225],
         [256, 289, 324, 361],
         [400, 441, 484, 529]]])

In [3]:
#指定求和张量的轴,先按第一个维度求和，即去掉一层括号，将剩下的矩阵按元素相加，也就消掉了2这个维度，得到一个3*4的矩阵
A_sum_0 = A.sum(axis=0)
A,A_sum_0,A_sum_0.shape

(tensor([[[ 0,  1,  2,  3],
          [ 4,  5,  6,  7],
          [ 8,  9, 10, 11]],
 
         [[12, 13, 14, 15],
          [16, 17, 18, 19],
          [20, 21, 22, 23]]]),
 tensor([[12, 14, 16, 18],
         [20, 22, 24, 26],
         [28, 30, 32, 34]]),
 torch.Size([3, 4]))

In [4]:
#按第二个维度进行求和，也就是去掉第二个维度，将矩阵变成一个2*4的矩阵
A_sum_1 = A.sum(axis=1)
A,A_sum_1,A_sum_1.shape

(tensor([[[ 0,  1,  2,  3],
          [ 4,  5,  6,  7],
          [ 8,  9, 10, 11]],
 
         [[12, 13, 14, 15],
          [16, 17, 18, 19],
          [20, 21, 22, 23]]]),
 tensor([[12, 15, 18, 21],
         [48, 51, 54, 57]]),
 torch.Size([2, 4]))

In [5]:
#也可以同时指定多个维度,将第一个和第二个维度分别消掉，变成一个含有4个元素的向量
A_sum_2 = A.sum(axis = [0,1])
A,A_sum_2,A_sum_2.shape

(tensor([[[ 0,  1,  2,  3],
          [ 4,  5,  6,  7],
          [ 8,  9, 10, 11]],
 
         [[12, 13, 14, 15],
          [16, 17, 18, 19],
          [20, 21, 22, 23]]]),
 tensor([60, 66, 72, 78]),
 torch.Size([4]))

In [6]:
#也可以在按维度求和后不丢掉维度，使用keepdims=True
A_sum_3 = A_sum_1.sum(axis = 0,keepdims = True)
A_sum_3,A_sum_3.shape

(tensor([[60, 66, 72, 78]]), torch.Size([1, 4]))

In [7]:
#torch.dot(x,y)表示两个矩阵的点积