In [1]:
'''
  参数管理
    访问参数，用于调试、诊断和可视化；
    参数初始化
    在不同模型组件间共享参数
'''
import torch
from torch import nn

#具有但隐藏层的多层感知机
net = nn.Sequential(nn.Linear(4,8),nn.ReLU(),nn.Linear(8,1))
X = torch.rand(size=(2,4))
net(X)

tensor([[-0.2935],
        [-0.2791]], grad_fn=<AddmmBackward0>)

In [5]:
#参数访问
print(net[2].state_dict())#当通过Sequential类定义模型时，我们可以通过索引来访问模型的任意层。每层的参数都在其属性中，这个例子所示，可以使用state_dict()方法检查第二个全连接层的参数


OrderedDict([('weight', tensor([[-0.2467, -0.1456, -0.1189, -0.2968, -0.0651,  0.3312, -0.1033,  0.2230]])), ('bias', tensor([-0.1418]))])


In [6]:
#每个参数都表示为参数类的一个实例，要对参数执行操作，需要访问底层的数值
print(type(net[2].bias))
print(net[2].bias)
print(net[2].bias.data)

<class 'torch.nn.parameter.Parameter'>
Parameter containing:
tensor([-0.1418], requires_grad=True)
tensor([-0.1418])


In [7]:
net[2].weight.grad == None

True