In [61]:
"""
汇聚层学习
也叫做池化层，目的是降低卷积层对位置的敏感性，降低对空间降采样表示的敏感性
常用的有两种汇聚方法：1，最大汇聚。2，平均汇聚
"""
import torch
from torch import nn
from d2l import torch as d2l

In [62]:
#实现汇聚层的前向传播
def pool2d(X,pool_size,mode='max'):
    p_h, p_w = pool_size
    Y = torch.zeros((X.shape[0] - p_h + 1, X.shape[1] - p_w + 1))
    for i in range(Y.shape[0]):
        for j in range(Y.shape[1]):
            if mode == 'max':
                Y[i,j] = X[i:i + p_h,j:j + p_w].max()
            elif mode == 'avg':
                Y[i,j] = X[i:i + p_h,j:j + p_w].mean()
    return Y

In [63]:
X = torch.tensor([[0.0, 1.0, 2.0], [3.0, 4.0, 5.0], [6.0, 7.0, 8.0]])
pool2d(X, (2, 2))

tensor([[4., 5.],
        [7., 8.]])

In [64]:
pool2d(X, (2, 2), 'avg')

tensor([[2., 3.],
        [5., 6.]])

In [65]:
"""
汇聚层的填充和步幅
"""
X = torch.arange(16,dtype=torch.float32).reshape((1,1,4,4))
X

tensor([[[[ 0.,  1.,  2.,  3.],
          [ 4.,  5.,  6.,  7.],
          [ 8.,  9., 10., 11.],
          [12., 13., 14., 15.]]]])

In [66]:
# 默认情况下，深度学习框架中的步幅与汇聚窗口的大小相同。 因此，如果我们使用形状为(3, 3)的汇聚窗口，那么默认情况下，我们得到的步幅形状为(3, 3)
pool2d = nn.MaxPool2d(3)#使用框架自带的汇聚层
pool2d(X),pool2d(X).shape#形状保持不变

(tensor([[[[10.]]]]), torch.Size([1, 1, 1, 1]))

In [67]:
#步幅和填充可以手动设定
pool2d = nn.MaxPool2d(3,padding=1,stride=2)#设置汇聚窗口大小为3，填充为1，步幅为2
pool2d(X)

tensor([[[[ 5.,  7.],
          [13., 15.]]]])

In [68]:
#可以设定一个任意大小的矩形汇聚窗口，并分别设定填充和步幅的高度和宽度
pool2d = nn.MaxPool2d((2, 3), stride=(2, 3), padding=(0, 1))
pool2d(X)

tensor([[[[ 5.,  7.],
          [13., 15.]]]])

In [69]:
X = torch.cat((X,X+1),1)#将X和X+1在第二个维度上拼接
X

tensor([[[[ 0.,  1.,  2.,  3.],
          [ 4.,  5.,  6.,  7.],
          [ 8.,  9., 10., 11.],
          [12., 13., 14., 15.]],

         [[ 1.,  2.,  3.,  4.],
          [ 5.,  6.,  7.,  8.],
          [ 9., 10., 11., 12.],
          [13., 14., 15., 16.]]]])

In [70]:
pool2d = nn.MaxPool2d(3, padding=1, stride=2)
pool2d(X)  #汇聚后的输出通道仍为2

tensor([[[[ 5.,  7.],
          [13., 15.]],

         [[ 6.,  8.],
          [14., 16.]]]])

In [70]:
"""
小结
对于给定输入元素，最大汇聚层会输出该窗口内的最大值，平均汇聚层会输出该窗口内的平均值。

汇聚层的主要优点之一是减轻卷积层对位置的过度敏感。

我们可以指定汇聚层的填充和步幅。

使用最大汇聚层以及大于1的步幅，可减少空间维度（如高度和宽度）。

汇聚层的输出通道数与输入通道数相同。

"""